

dataObj.placeholders = {
  "placeholder_1": "<div class='draggable resizable'><div id='field-group-1'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam?</div></div>",
  "placeholder_2": "<div class='draggable resizable'><div id='field-group-2'>Duis aute irure dolor in reprehenderit in voluptate</div></div>",
  "placeholder_3": "<div class='draggable resizable'><div id='field-group-3'>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div></div>",
  "imageSlider": "<div class='draggable resizable'><div id='image-slider'></div></div>",
  "randomImage": "<div class='draggable resizable'><img src='https://picsum.photos/200/200?random=4' /></div>",
  "jumboImage": "<div class='draggable resizable'><div class='resizable '><img src='https://images.unsplash.com/photo-1591084728795-1149f32d9866?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1364&q=80' /></div></div>",
  "timeOffRequest": "<div class='draggable resizable'><h1 class='resizable'>Time Off Request</h1><p>Digital Harbor time off policy requires you to submit a time off request.</p><h6>Review the policy</h6></div>",
  "headingPersonalInfo": "<div class='draggable resizable'><h2><b>PERSONAL</b> INFORMATION</h2></div>",
  "subHeadingPersonalInfo": "<div class='draggable resizable'><h2>WHY</h2><p>It is very important that we understand the purpose of this time off to ensure our records are correct.</p></div>",
  "subHeadingWhen": "<div class='draggable resizable'><h2>WHEN</h2></div>",
  "dhLogo": "<div class='draggable resizable'><img src='https://static.ambitionbox.com/assets/v2/images/rs:fit:1280:960:false:false/bG9jYWw6Ly8vbG9nb3Mvb3JpZ2luYWxzL2RpZ2l0YWwtaGFyYm9yLmpwZw.png' /></div>",
  "squareImage1": "<div class='draggable resizable'><img src='https://picsum.photos/400/400' alt='Lorem Picsum Image'></div>",
  "squareImage2": "<div class='draggable resizable'><img src='https://picsum.photos/400/400' alt='Lorem Picsum Image'></div>",
  "squareImage3": "<div class='draggable resizable'><img src='https://picsum.photos/400/400' alt='Lorem Picsum Image'></div>",
  "squareImage4": "<div class='draggable resizable'><img src='https://picsum.photos/400/400' alt='Lorem Picsum Image'></div>",
  "squareImage5": "<div class='draggable resizable'><img src='https://picsum.photos/400/400' alt='Lorem Picsum Image'></div>",
  "verticalRectangleImage1": "<div class='draggable resizable'><img src='https://picsum.photos/400/600' alt='Lorem Picsum Image'></div>",
  "verticalRectangleImage2": "<div class='draggable resizable'><img src='https://picsum.photos/400/600' alt='Lorem Picsum Image'></div>",
  "verticalRectangleImage3": "<div class='draggable resizable'><img src='https://picsum.photos/400/600' alt='Lorem Picsum Image'></div>",
  "verticalRectangleImage4": "<div class='draggable resizable'><img src='https://picsum.photos/400/600' alt='Lorem Picsum Image'></div>",
  "verticalRectangleImage5": "<div class='draggable resizable'><img src='https://picsum.photos/400/600' alt='Lorem Picsum Image'></div>",
  "horizontalRectangleImage1": "<div class='draggable resizable'><img src='https://picsum.photos/seed/2/600/400' alt='Lorem Picsum Image'></div>",
  "horizontalRectangleImage2": "<div class='draggable resizable'><img src='https://picsum.photos/seed/44/600/400' alt='Lorem Picsum Image'></div>",
  "horizontalRectangleImage3": "<div class='draggable resizable'><img src='https://picsum.photos/seed/3/600/400' alt='Lorem Picsum Image'></div>",
  "horizontalRectangleImage4": "<div class='draggable resizable'><img src='https://picsum.photos/seed/7/600/400' alt='Lorem Picsum Image'></div>",
  "horizontalRectangleImage5": "<div class='draggable resizable'><img src='https://picsum.photos/seed/44/600/400' alt='Lorem Picsum Image'></div>",
  "snippet1": "<div class='draggable resizable'><h1>Welcome!</h1></div>",
  "snippet2": "<div class='draggable resizable'><p>Lorem ipsum dolor sit amet.</p></div>",
  "snippet3": "<div class='draggable resizable'><div class='container '><h2>Title</h2><p>Content</p></div></div>",
  "snippet4": "<div class='draggable resizable'><img src='path/to/image.jpg' alt='Image'></div>",
  "snippet5": "<div class='draggable resizable'><ul><li>Item 1</li><li>Item 2</li><li>Item 3</li></ul></div>",
  "snippet6": "<div class='draggable resizable'><a href='https://example.com'>Visit our website</a></div>",
  "snippet7": "<div class='draggable resizable'><input type='text' placeholder='Enter your name'></div>",
  "snippet8": "<div class='draggable resizable'><div class='alert '>Error: Something went wrong!</div></div>",
  "snippet9": "<div class='draggable resizable'><h3>Section Heading</h3><p>Section content goes here.</p></div>",
  "snippet10": "<div class='draggable resizable'><button>Click me</button></div>",
  "snippet11": "<div class='draggable resizable'><span class='highlight '>Highlighted text</span></div>",
  "snippet12": "<div class='draggable resizable'><form><input type='email' placeholder='Enter your email'></form></div>",
  "snippet13": "<div class='draggable resizable'><blockquote>Quote of the day</blockquote></div>",
  "snippet14": "<div class='draggable resizable'><video src='path/to/video.mp4' controls></video></div>",
  "snippet15": "<div class='draggable resizable'><table><tr><th>Header 1</th><th>Header 2</th></tr><tr><td>Data 1</td><td>Data 2</td></tr></table></div>",
  "snippet16": "<div class='draggable resizable'><div class='card '><img src='path/to/image.jpg' alt='Card image'><h3>Card Title</h3><p>Card content</p></div></div>",
  "snippet17": "<div class='draggable resizable'><h2>Section Title</h2><p>Section content goes here.</p></div>",
  "snippet18": "<div class='draggable resizable'><label for='name'>Name: <input type='text' id='name'></label></div>",
  "snippet19": "<div class='draggable resizable'><audio src='path/to/audio.mp3' controls></audio></div>",
  "snippet20": "<div class='draggable resizable'><textarea placeholder='Enter your message'></textarea></div>",
  "snippet21": "<div class='draggable resizable'>    <div style='border: 1px solid #ccc; border-radius: 4px;'>      <div style='background-color: #f5f5f5; padding: 10px;'>        <h3 style='margin: 0; font-size: 18px;'>Card Title</h3>        <img src='https://picsum.photos/600/400' alt='Lorem Picsum Image'>      </div>      <div id='cardContent' style='padding: 10px;'>        <p style='font-size: 14px; line-height: 1.5;'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>      </div>    </div>  </div>",
  "snippet22": "<div class='draggable resizable'>    <div style='display: flex; align-items: center; justify-content: center; background-color: #f5f5f5; width: 300px; height: 200px;'>      <h2 style='font-size: 24px; color: #333;'>Centered Content</h2>    </div>  </div>",
  "snippet23": "<div class='draggable resizable'>    <div style='background-color: #f5f5f5; border: 1px solid #ccc; border-radius: 4px; padding: 20px;'>      <h3 style='margin: 0; font-size: 18px;'>Info Box</h3>      <p style='font-size: 14px; margin-top: 10px;'>This is an information box with some important details.</p>      <a href='#' style='color: #007bff; text-decoration: none;'>Read More</a>    </div>  </div>",
  "collapsibleCard": "<div class='draggable resizable'>    <div style='border: 1px solid #ccc; border-radius: 4px;'>      <div style='background-color: #f5f5f5; padding: 10px;'>        <h3 style='margin: 0; font-size: 18px;'>Collapsible Card</h3>        <button onclick='toggleCardContent(this)' style='background-color: #f5f5f5; border: none; float: right;'>Collapse</button>      </div>      <div id='collapsibleCardContent' style='padding: 10px; display: none;'>        <p style='font-size: 14px; line-height: 1.5;'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>        <img src='https://placeimg.com/400/200/tech' alt='Image' style='width: 100%; max-width: 400px; height: auto;'>      </div>    </div>    <script>      function toggleCardContent(button) {        const contentDiv = button.parentElement.nextElementSibling;        contentDiv.style.display = contentDiv.style.display === 'none' ? 'block' : 'none';      }    </script>  </div>",
  "snippet24": "<div class='draggable resizable'>    <div style='background-color: #f8f9fa; padding: 20px;'>      <h2 style='font-size: 24px; color: #333;'>Gradient Background</h2>      <p style='font-size: 16px; line-height: 1.5;'>This is a beautiful snippet with a gradient background.</p>      <button style='background: linear-gradient(45deg, #ff416c, #ff4b2b); color: #fff; border: none; padding: 10px 20px; border-radius: 4px;'>Click Me</button>    </div>  </div>",
  "snippet25": "<div class='draggable resizable'>    <div style='background-color: #fff; border: 1px solid #ddd; border-radius: 4px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);'>      <img src='https://placeimg.com/400/200/nature' alt='Image' style='width: 100%; max-width: 400px; height: auto;'>      <div style='padding: 20px;'>        <h3 style='font-size: 18px; color: #333;'>Image Overlay</h3>        <p style='font-size: 14px;'>This snippet features an image with an overlay.</p>      </div>    </div>  </div>",
  "snippe26": "<div class='draggable resizable'>    <div style='background-color: #f5f5f5; padding: 20px; border-radius: 4px;'>      <h3 style='font-size: 18px; color: #333;'>Feature Box</h3>      <p style='font-size: 14px;'>This is a feature box with a nice background color.</p>      <div style='display: flex; align-items: center; margin-top: 15px;'>        <i class='fas fa-check-circle' style='color: #34c38f; font-size: 24px; margin-right: 10px;'></i>        <p style='font-size: 14px;'>Feature 1</p>      </div>      <div style='display: flex; align-items: center; margin-top: 15px;'>        <i class='fas fa-check-circle' style='color: #34c38f; font-size: 24px; margin-right: 10px;'></i>        <p style='font-size: 14px;'>Feature 2</p>      </div>    </div>  </div>",
  "snippet27": "<div class='draggable resizable'>    <div style='background-color: #f9f9f9; padding: 20px; border-radius: 4px;'>      <h3 style='font-size: 18px; color: #333;'>Testimonial Card</h3>      <div style='display: flex; align-items: center; margin-top: 15px;'>        <img src='https://placeimg.com/50/50/people' alt='Avatar' style='width: 50px; height: 50px; border-radius: 50%; margin-right: 10px;'>        <div>          <p style='font-size: 14px; margin-bottom: 5px;'><b>John Doe</b></p>          <p style='font-size: 12px; color: #888;'>CEO, Company Name</p>        </div>      </div>      <p style='font-size: 14px; margin-top: 15px;'>'This is a testimonial card with a beautiful design.'</p>    </div>  </div>",
  "snippet28": "<div class='draggable resizable'>    <div style='background-color: #fff; border: 1px solid #ddd; border-radius: 4px; padding: 20px;'>      <h3 style='font-size: 18px; color: #333;'>Feature Comparison</h3>      <table style='width: 100%; margin-top: 15px;'>        <tr>          <th style='text-align: left;'>Features</th>          <th>Basic</th>          <th>Pro</th>        </tr>        <tr>          <td style='text-align: left;'>Feature 1</td>          <td><i class='fas fa-check' style='color: #34c38f;'></i></td>          <td><i class='fas fa-check' style='color: #34c38f;'></i></td>        </tr>        <tr>          <td style='text-align: left;'>Feature 2</td>          <td><i class='fas fa-check' style='color: #34c38f;'></i></td>          <td><i class='fas fa-check' style='color: #34c38f;'></i></td>        </tr>      </table>    </div>  </div>"
};
